/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFaArrowLeft: typeof import('~icons/fa/arrow-left')['default']
    IconFaEllipsisV: typeof import('~icons/fa/ellipsis-v')['default']
    IconFaLock: typeof import('~icons/fa/lock')['default']
    IconFaMaximize: typeof import('~icons/fa/maximize')['default']
    IconFaMinimize: typeof import('~icons/fa/minimize')['default']
    IconFaMinus: typeof import('~icons/fa/minus')['default']
    IconFaMoonO: typeof import('~icons/fa/moon-o')['default']
    IconFaPlus: typeof import('~icons/fa/plus')['default']
    IconFaSonO: typeof import('~icons/fa/son-o')['default']
    IconFaSun: typeof import('~icons/fa/sun')['default']
    IconFaSunO: typeof import('~icons/fa/sun-o')['default']
    IconFaSymbolsUnlock: typeof import('~icons/fa/symbols-unlock')['default']
    IconFaUnlock: typeof import('~icons/fa/unlock')['default']
    IconFaWindow: typeof import('~icons/fa/window')['default']
    IconFaWindowMaximize: typeof import('~icons/fa/window-maximize')['default']
    IconFaWindowMinimize: typeof import('~icons/fa/window-minimize')['default']
    IconLucideMaximize: typeof import('~icons/lucide/maximize')['default']
    IconLucideMinimize: typeof import('~icons/lucide/minimize')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucideMoonO: typeof import('~icons/lucide/moon-o')['default']
    IconLucideShoppingCart: typeof import('~icons/lucide/shopping-cart')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconMaterialSymbolsLock: typeof import('~icons/material-symbols/lock')['default']
    IconMaterialSymbolsUnlock: typeof import('~icons/material-symbols/unlock')['default']
  }
}
