/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFaArrowDown: typeof import('~icons/fa/arrow-down')['default']
    IconFaArrowLeft: typeof import('~icons/fa/arrow-left')['default']
    IconFaArrowRight: typeof import('~icons/fa/arrow-right')['default']
    IconFaArrowUp: typeof import('~icons/fa/arrow-up')['default']
    IconFaCar: typeof import('~icons/fa/car')['default']
    IconFaCog: typeof import('~icons/fa/cog')['default']
    IconFaCogO: typeof import('~icons/fa/cog-o')['default']
    IconFaEllipsisV: typeof import('~icons/fa/ellipsis-v')['default']
    IconFaExclamationTriangle: typeof import('~icons/fa/exclamation-triangle')['default']
    IconFaInfoCircle: typeof import('~icons/fa/info-circle')['default']
    IconFaLock: typeof import('~icons/fa/lock')['default']
    IconFaMapMarker: typeof import('~icons/fa/map-marker')['default']
    IconFaMinus: typeof import('~icons/fa/minus')['default']
    IconFaMoonO: typeof import('~icons/fa/moon-o')['default']
    IconFaPlus: typeof import('~icons/fa/plus')['default']
    IconFaSunO: typeof import('~icons/fa/sun-o')['default']
    IconFaTrash: typeof import('~icons/fa/trash')['default']
    IconFaTrashO: typeof import('~icons/fa/trash-o')['default']
    IconFaUnlock: typeof import('~icons/fa/unlock')['default']
    IconFaWindowMaximize: typeof import('~icons/fa/window-maximize')['default']
    IconFaWindowMinimize: typeof import('~icons/fa/window-minimize')['default']
    IconFaWrench: typeof import('~icons/fa/wrench')['default']
    IconTeenyiconsBackspace: typeof import('~icons/teenyicons/backspace')['default']
    IconTeenyiconsBackspaceOutline: typeof import('~icons/teenyicons/backspace-outline')['default']
    IconTeenyiconsBackspaceOutlineIcon: typeof import('~icons/teenyicons/backspace-outline-icon')['default']
    IconTeenyiconsEnter: typeof import('~icons/teenyicons/enter')['default']
    IconTeenyiconsEnterOutline: typeof import('~icons/teenyicons/enter-outline')['default']
    'IconTeenyiconsUil-': typeof import('~icons/teenyicons/uil-')['default']
    IconTeenyiconsUilBackspace: typeof import('~icons/teenyicons/uil-backspace')['default']
    IconUilBackspace: typeof import('~icons/uil/backspace')['default']
    IconUilEnter: typeof import('~icons/uil/enter')['default']
    IconUilRed: typeof import('~icons/uil/red')['default']
    IconUilRedo: typeof import('~icons/uil/redo')['default']
  }
}
